# Generated by Django 5.0.6 on 2024-06-06 15:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('ActorID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('BirthYear', models.IntegerField()),
                ('Nationality', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('DirectorID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('BirthYear', models.IntegerField()),
                ('Nationality', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('MovieID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('ReleaseYear', models.IntegerField()),
                ('Genre', models.CharField(max_length=100)),
                ('Rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('Director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_api.director')),
            ],
        ),
        migrations.CreateModel(
            name='MovieActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ActorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_api.actor')),
                ('MovieID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_api.movie')),
            ],
            options={
                'unique_together': {('MovieID', 'ActorID')},
            },
        ),
    ]
