# Generated by Django 5.0.6 on 2024-06-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Rating',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
