# Generated by Django 5.0.6 on 2024-06-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='BirthYear',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='Nationality',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
