# Generated by Django 5.0.6 on 2024-06-06 17:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_api', '0003_alter_actor_birthyear_alter_actor_nationality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('GenreID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='Genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='Genres',
            field=models.ManyToManyField(to='movie_api.genre'),
        ),
    ]
