# Generated by Django 5.0.6 on 2024-06-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_api', '0004_genre_remove_movie_genre_movie_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Genres',
            field=models.ManyToManyField(null=True, to='movie_api.genre'),
        ),
    ]
